# Generated by Django 3.2.12 on 2024-11-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='little_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
