# Generated by Django 3.2.12 on 2024-11-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20241106_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_posted']},
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
